name: "Merge"
description: "Merge images"
inputs:
  tags:
    description: "Tags"
    required: false
    default: ""
  image:
    description: "Image target"
    required: true

runs:
  using: "composite"
  steps:
    - name: Merge digests and reupload
      uses: actions/upload-artifact/merge@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: digests
        pattern: single-digest-*

    - name: Download merged digests
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: digests
        path: /tmp/digests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
      with:
        images: ${{ inputs.image }}
        tags: ${{ inputs.tags }}

    - name: Create manifest list and push
      working-directory: /tmp/digests
      shell: bash
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
