{
 "title": "Overview Dash",
 "description": "A high level overview of your car",
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "car",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   }
  ]
 },
 "panels": [
  { "title": "$car", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "car" },
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  battery_level,\r\n       date\r\nFROM\r\n  positions\r\n  WHERE\r\n car_id = $car\r\nunion\r\nselect battery_level, date\r\nfrom charges c\r\njoin\r\n  charging_processes p ON p.id = c.charging_process_id \r\nWHERE\r\n  $__timeFilter(date) and\r\n  p.car_id = $car\r\norder by date desc\r\nlimit 1 "
    }
   ]
  },
  {
   "title": "Charging Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  case when date > NOW() - INTERVAL '5 min' then charger_voltage else 0 end as \"Charging Voltage [V]\"\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  p.car_id = $car\nORDER BY\n  date desc"
    }
   ]
  },
  {
   "title": "Charging kW",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\ncase when date > NOW() - INTERVAL '5 min' then charger_power else 0 end as \"Power [kW]\"\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  p.car_id = $car\nORDER BY\n  date desc"
    }
   ]
  },
  {
   "title": "Charge Level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "select $__time(date), battery_level AS \"SOC [%]\"\r\nfrom\r\n    (SELECT\r\n    battery_level\r\n        , date\r\n    FROM\r\n    positions\r\n    WHERE\r\n    car_id = $car AND\r\n    $__timeFilter(date)\r\n    UNION ALL\r\n    select\r\n    battery_level\r\n        , date\r\n    from charges c\r\njoin\r\n  charging_processes p ON p.id = c.charging_process_id \r\nWHERE\r\n  $__timeFilter(date) and\r\n  p.car_id = $car) as data\r\nORDER BY\r\n    date ASC"
    }
   ]
  },
  {
   "title": "Ideal Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select $__time(date), Range\nfrom\n(\nSELECT\n\tdate,\n\tconvert_km(ideal_battery_range_km, '$length_unit') AS Range\nFROM\n\tpositions\nWHERE\n car_id = $car\n\nUNION ALL\nselect date,\nconvert_km(ideal_battery_range_km, '$length_unit') AS Range\nfrom charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  p.car_id = $car\n\n ) as data\n \nORDER BY\n\tdate DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "WITH summary AS (\n\tSELECT\n\t\tdate,\n\t\todometer,\n\t\trank() OVER (PARTITION BY date_trunc('hour', date) ORDER BY date DESC) AS rk\n\t\tFROM\n\t\t\tpositions\n\t\tWHERE\n\t\t\tcar_id = $car\n)\nSELECT\n date as time,\n convert_km(odometer, '$length_unit') as \"mileage [$length_unit]\"\nFROM\n\tsummary\nWHERE\n\trk = 1\n\torder by date DESC\n\tlimit 1"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select version from updates where car_id = $car order by start_date desc limit 1"
    }
   ]
  },
  {
   "title": "Charging Details",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  charger_power as \"Power [kW]\",\n  charger_actual_current as \"Current [A]\"\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date) and\n  p.car_id = $car\nORDER BY\n  date ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(date),\n  charger_voltage as \"Charging Voltage [V]\"\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date) and\n  p.car_id = $car\nORDER BY\n  date ASC"
    }
   ]
  },
  {
   "title": "Driver Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n\t$__time(date),\n\tconvert_celsius(driver_temp_setting, '$temp_unit') as \"Driver Temperature [°$temp_unit]\"\n\nFROM\n\tpositions\nWHERE\n car_id = $car\nORDER BY\n\tdate DESC"
    }
   ]
  },
  {
   "title": "Outside Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\ndate,\n  convert_celsius(outside_temp, '$temp_unit') AS \"Outside Temperature [°$temp_unit]\"\nFROM\n  positions\nWHERE\n  car_id = $car\n  and outside_temp is not null\norder by date desc\nlimit 1 "
    }
   ]
  },
  {
   "title": "Inside Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\ndate,\n  convert_celsius(inside_temp, '$temp_unit') AS \"Inside Temperature [°$temp_unit]\"\nFROM\n  positions\nWHERE\n  car_id = $car\n  and inside_temp is not null\norder by date desc\nlimit 1 "
    }
   ]
  }
 ]
}