[server]
# Protocol (http, https, h2, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr =

# The http port to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = localhost

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = %(protocol)s://%(domain)s:%(http_port)s/

# Log web requests
router_logging = false

# the path relative working path
static_root_path = public

# enable gzip
enable_gzip = false

# https certs & key file
cert_file =
cert_key =

# Unix socket path
socket =

[database]
# You can configure the database connection by specifying type, host, name, user and password
# as separate properties or as on string using the url properties.

# Either "mysql", "postgres" or "sqlite3", it's your choice
type = sqlite3

# The file path when using sqlite3
path = grafana.db

# The name of the default database (for legacy reasons, this is called `name` rather than `database`)
# For sqlite3 this will be used as the database file name
# For mysql and postgres this is the database name
name = grafana.db

# Connection string for connecting to a database.
# PostgreSQL: postgres://user:password@localhost:5432/database?sslmode=disable
# MySQL: mysql://user:password@localhost:3306/database?collation=utf8mb4_unicode_ci
# SQLite3: file:/path/to/grafana.db
url =

# Max idle conn setting default is 2
max_idle_conn = 2

# Max conn setting default is 0 (mean not set)
max_open_conn =

# Connection Max Lifetime default is 14400 (means 14400 seconds or 4 hours)
conn_max_lifetime = 14400

# Set to true to log the sql calls and execution times.
log_queries =

# For "postgres", use either "disable", "require", "verify-ca" or "verify-full".
# For "mysql", use either "true", "false", or "skip-verify".
ssl_mode = disable

# For "postgres", use either "disable", "require", "verify-ca" or "verify-full".
# For "mysql", use either "true", "false", or "skip-verify".
ca_cert_path =
client_key_path =
client_cert_path =
server_cert_name =

# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password =

# Use either URL or the previous fields to configure the database
# Example: mysql://user:password@hostname/filename?charset=utf8mb4&parseTime=true
# The $ character can be used in the URL to reference environment variables.
url =

# For "sqlite3" only, news path to database file
path =

[session]
# Either "memory", "file", "redis", "mysql", "postgres", "memcache", or "database" default is "file"
provider = file

# Provider config options
# memory: not have any config yet
# file: session dir path, is relative to grafana data_path
# redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
# mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`
# postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
# memcache: 127.0.0.1:11211
# database: will use existing database configuration
provider_config = sessions

# Session cookie name
cookie_name = grafana_sess

# If you use session in https only, default is false
cookie_secure = false

# Session life time, default is 86400 (24 hours)
session_life_time = 86400

# Limit the maximum lifetime of a session, default is 30 days
session_life_time_max = 86400

[analytics]
reporting_enabled = false
check_for_updates = false

[security]
# disable creation of admin user on first start of grafana
disable_initial_admin_creation = false

# default admin user, created on startup
admin_user = admin

# default admin password, can be changed before first start of grafana, or in profile settings
admin_password = admin

# used for signing
secret_key = SW2YcwTIb9zpOOhoPsMm

# disable gravatar profile images
disable_gravatar = false

# data source proxy whitelist (ip_or_domain:port separated by spaces)
data_source_proxy_whitelist =

# disable protection against brute force login attempts
disable_brute_force_login_protection = false

# set to true if you host Grafana behind HTTPS. default is false.
cookie_secure = false

# set cookie SameSite attribute. defaults to `lax`. can be set to "lax", "strict", "none" or "disabled"
cookie_samesite = lax

# set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>. default is false.
allow_embedding = false

# If enabled, only users with either the organization admin role, or the Grafana server admin role will be able to modify
# data sources. Defaults to false
datasources_require_admin = false

[snapshots]
# snapshot sharing options
external_enabled = true
external_snapshot_url = https://snapshots-origin.raintank.io
external_snapshot_name = Publish to snapshots-origin.raintank.io

# Set to true to enable this Grafana instance act as an external snapshot server and allow unauthenticated requests for
# creating and deleting snapshots.
public_mode = false

# remove expired snapshot
snapshot_remove_expired = true

[users]
# disable user signup / registration
allow_sign_up = false

# Allow non admin users to create organizations
allow_org_create = false

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true

# Set this value to automatically add new users to the provided org.
auto_assign_org_id = 1

# Default role new users will be automatically assigned (if disabled above is set to true)
auto_assign_org_role = Viewer

# Require email validation before sign up completes
verify_email_enabled = false

# Background text for the user field on the login page
login_hint = email or username
login_default_org_name = Main Org.

# Default UI theme ("dark" or "light")
default_theme = light

# Path to a custom home page. Users are only redirected to this if the default home dashboard is used. It should match a frontend route and contain a leading slash.
home_dashboard_uid =

[auth]
# Login cookie name
login_cookie_name = grafana_session

# The maximum lifetime (duration) an authenticated user can be inactive before being required to login at next visit. Default is 7 days (168h). This setting should be expressed as a duration, e.g. 5m (minutes), 6h (6 hours). The lifetime resets at each successful token rotation.
login_maximum_inactive_lifetime_duration =

# The maximum lifetime (duration) an authenticated user can be logged in since login time before being required to login. Default is 30 days (720h). This setting should be expressed as a duration, e.g. 5m (minutes), 6h (6 hours).
login_maximum_lifetime_duration =

# How often should auth tokens be rotated for authenticated users when being active. The default is each 10 minutes.
token_rotation_interval_minutes = 10

# Set to true to disable (hide) the login form, useful if you use OAuth, defaults to false
disable_login_form = false

# Set to true to disable the sign out link in the side menu. useful if you use auth.proxy or auth.jwt, defaults to false
disable_signout_menu = false

# URL to redirect the user to after sign out
signout_redirect_url =

# Set to true to attempt login with OAuth automatically, skipping the login screen.
# This setting is ignored if multiple OAuth providers are configured.
oauth_auto_login = false

# OAuth state max age, defaults to 600 seconds (10 minutes)
oauth_state_cookie_max_age = 600

[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = Main Org.

# specify role for unauthenticated users
org_role = Viewer

# mask the Grafana version number for unauthenticated users
hide_version = false

[auth.basic]
enabled = true

[auth.proxy]
enabled = false

[log]
# Either "console", "file", "syslog". Default is console and file
# Use space to separate multiple modes, e.g. "console file"
mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
level = info

# optional settings to set different levels for specific loggers. Ex filters = sqlstore:debug
filters =

[log.console]
# log line format, valid options are text, console and json
format = console

# This enables automated log rotate(switch of following options), default is true
log_rotate = true

# Max line number of single file, default is 1000000
max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB, default is 28
max_size_shift = 28

# Segment log line with log level once it has been specified.
log_rotate = true

# Expired days of log file(delete after max days), default is 7
max_days = 7

[log.file]
# log line format, valid options are text, console and json
format = text

# This enables automated log rotate(switch of following options), default is true
log_rotate = true

# Max line number of single file, default is 1000000
max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB, default is 28
max_size_shift = 28

# Segment log line with log level once it has been specified.
log_rotate = true

# Expired days of log file(delete after max days), default is 7
max_days = 7

[metrics]
enabled = true
interval_seconds = 10
basic_auth_username =
basic_auth_password =

[metrics.graphite]
# Enable by setting the address setting (ex localhost:2003)
address =
prefix = prod.grafana.%(instance_name)s.

[grafana_net]
url = https://grafana.net

[tracing.jaeger]
# Enable by setting the address sending traces to jaeger (ex localhost:14268)
address = localhost:14268
# Tag that will always be included in when creating new spans. ex (tag1:value1,tag2:value2)
always_included_tag = tag1:value1
# Type specifies the type of the sampler: const, probabilistic, rateLimiting, remote
sampler_type = const
# Sampler configuration parameter
sampler_param = 1

[external_image_storage]
# Used for uploading images to public servers so they can be included in slack messages and emails
provider =

[external_image_storage.s3]
bucket =
region =
path =
access_key =
secret_key =

[external_image_storage.webdav]
url =
username =
password =

[external_image_storage.gcs]
key_file =
bucket =
path =

[external_image_storage.azure_blob]
account_name =
account_key =
container_name =

[rendering]
# Options to configure a remote HTTP image rendering service, e.g. using https://github.com/grafana/grafana-image-renderer.
# URL to a remote HTTP image renderer service, e.g. http://localhost:8081/render, will enable Grafana to render panels and dashboards to PNG-images using HTTP requests to an external service.
server_url =
# If the remote HTTP image renderer service runs on a different server than the Grafana server you may have to configure this to a URL where Grafana is reachable, e.g. http://grafana.domain.com/
callback_url =

[panels]
# If set to true Grafana will allow script tags in text panels. Not recommended as it enable XSS vulnerabilities.
disable_sanitize_html = false

[plugins]
allow_loading_unsigned_plugins =

[alerting]
# Disable alerting engine & UI features
enabled = false
# Makes it so that alert rules can not be edited in the UI
# If set to true, all alert rules will be executed but you will not be able to edit them in the UI
disable_editing = true
# Makes it possible to disable alert rule execution but leaving the UI features enabled
# If set to true, you will not be able to execute any alert rules but you will be able to edit them in the UI
execution_disable = true
# Alert rules are evaluated in groups. The number of goroutines used to evaluate rules in parallel is the minimum of this value and the number of rules.
evaluation_timeout_seconds = 30
notification_timeout_seconds = 30
max_attempts = 3
min_interval_seconds = 1

# Default setting for new alert rules. Defaults to "(no value)".
default_rule_evaluation_timeout = 30s

[annotations]
# Configures the batch size for the annotation clean up job. This setting is used for dashboard, API, and alert annotations.
cleanupjob_batchsize = 100

[annotations.dashboard]
# Dashboard annotations means that annotations are associated with the dashboard they are created on.

# Configures how long dashboard annotations are stored. Default is 0, which keeps them forever.
# This setting should be expressed as a duration. Examples: 6h (hours), 2d (days), 1w (week). Available units: h (hours), d (days), w (weeks), M (months).
max_age =

# Configures the maximum number of dashboard annotations that Grafana stores. Default is 0, which keeps all dashboard annotations.
max_annotations_to_keep =

[annotations.api]
# API annotations means that the annotations have been created using the API without any
# association with a dashboard.

# Configures how long API annotations are stored. Default is 0, which keeps them forever.
# This setting should be expressed as a duration. Examples: 6h (hours), 2d (days), 1w (week). Available units: h (hours), d (days), w (weeks), M (months).
max_age =

# Configures the maximum number of API annotations that Grafana stores. Default is 0, which keeps all API annotations.
max_annotations_to_keep =

[explore]
# Enable the Explore section
enabled = true

[help]
# Enable the Help section
enabled = true

[profile]
# Enable the Profile section
enabled = true

[query_history]
# Enable the Query history
enabled = true

[internal_metrics]
# Enable internal metrics
enabled = true

# Write internal metrics to graphite
graphite_address = localhost:2003
graphite_prefix = grafana.internal_metric.%(instance_name)s.

[feature_toggles]
# enable features, separated by spaces
enable =

[date_formats]
# For information on what formatting patterns that are supported https://momentjs.com/docs/#/displaying/

# Default system date format used in time range picker and other places where full time is displayed
full_date = YYYY-MM-DD HH:mm:ss

# Used by the time range picker and for the current time
interval_second = HH:mm:ss
interval_minute = HH:mm
interval_hour = MM/DD HH:mm
interval_day = MM/DD
interval_month = YYYY-MM
interval_year = YYYY

# Experimental feature
use_browser_locale = false

# Default timezone for user preferences. Options are 'browser' for the browser local timezone or a timezone name from IANA Time Zone database, e.g. 'UTC' or 'Europe/Amsterdam' etc.
default_timezone = browser

[expressions]
# Enable the expressions feature with feature toggle
enabled = true

[geomap]
# Set the JSON configuration for the geomap
default_baselayer_config = {"type":"xyz","config":{"attribution":"Open street map","url":"https://tile.openstreetmap.org/{z}/{x}/{y}.png"}}

[unified_alerting]
enabled = false
