{
 "title": "Effizienz",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "car", "label": "Auto", "query": "select id from cars;" }
  ]
 },
 "panels": [
  {
   "title": "Ø-Verbrauch (netto)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \n  sum(\"consumption_kWh\") / sum(distance) * 100\nfrom trips \nwhere \n  distance is not null \n  and \"consumption_kWh\" is not null\n  and car_id = $car"
    }
   ]
  },
  {
   "title": "Ø-Verbrauch (brutto) ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "WITH d1 AS (\n\tSELECT\n\t\tc.car_id,\n\t\tlag(end_range_km) OVER (ORDER BY start_date) - start_range_km AS range_loss,\n\t\tp.odometer - lag(p.odometer) OVER (ORDER BY start_date) AS distance\n\tFROM\n\t\tcharging_processes c\n\tLEFT JOIN positions p ON p.id = c.position_id \n\tWHERE\n\t  end_date IS NOT NULL AND\n\t  c.car_id = $car\n\tORDER BY\n\t\tstart_date\n),\nd2 AS (\nSELECT\n\tcar_id,\n\tsum(range_loss) AS range_loss,\n\tsum(distance) AS distance\nFROM\n\td1\nWHERE\n\tdistance >= 0 AND range_loss >= 0\nGROUP BY\n\tcar_id\n)\nSELECT\n\trange_loss * c.efficiency / distance * 100\nFROM\n\td2\n\tLEFT JOIN cars c ON c.id = car_id"
    }
   ]
  },
  {
   "title": "Geloggte Distanz",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select sum(distance) from trips where car_id = $car;"
    }
   ]
  },
  {
   "title": "Temperatur – Effizienz",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH t AS (\n\tSELECT\n\t\tROUND(cast(outside_temp_avg AS numeric) / 5, 0) * 5 AS outside_temp,\n\t\tsum(\"consumption_kWh\") AS total_consumption,\n\t\tsum(distance) AS total_distance,\n\t\tsum(duration_min) as duration,\n\t\tcar_id\n\tFROM\n\t\ttrips\n\tWHERE\n\t\tdistance IS NOT NULL\n\t\tAND \"consumption_kWh\" IS NOT NULL\n\t\tAND car_id = $car\n\tGROUP BY\n\t\t1,\n\t\tcar_id\n)\n\nSELECT\n\toutside_temp,\n\ttotal_consumption / total_distance * 100 AS consumption,\n\t(total_consumption / total_distance) / c.efficiency AS efficiency,\n\ttotal_distance,\n\t(total_distance / duration) * 60 as avg_speed\nFROM\n\tt\nJOIN cars c ON t.car_id = c.id"
    }
   ]
  }
 ]
}