{
 "title": "Zustände",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Letzte Zustandsänderung",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select $__time(start_date), state from states order by start_date desc limit 1;"
    }
   ]
  },
  {
   "title": "Aktueller Zustand",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select $__time(start_date), state from states order by start_date desc limit 1;"
    }
   ]
  },
  {
   "title": "Standzeit (%)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select 1 - sum(duration_min) / (EXTRACT(EPOCH FROM (max(end_date) - min(start_date))) / 60), 1 as time from trips"
    }
   ]
  },
  {
   "title": "Zustandsverlauf",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select\n$__time(start_date),\ncase \n  when state = 'offline' then 0\n  when state = 'asleep'  then 1\n  when state = 'online'  then 2\nend as \"Zustand\"\nfrom states\nwhere $__timeFilter(start_date);"
    }
   ]
  }
 ]
}