name: "Setup Elixir and Cache Dependencies"
description: "Setup Elixir, OTP and cache dependencies"
inputs:
  elixir-version:
    description: "Elixir version"
    required: false
    default: "1.19.5"
  otp-version:
    description: "OTP version"
    required: false
    default: "26"
  cache-name-deps:
    description: "Cache name for dependencies"
    required: true
  cache-name-compiled:
    description: "Cache name for compiled build"
    required: true
  mix-env:
    description: "Mix environment"
    required: false
    default: "dev"
  ELIXIR_ASSERT_TIMEOUT:
    description: "Elixir assert timeout"
    required: false
    default: "1000"
outputs:
  elixir-version:
    description: "The Elixir version used in the setup"
    value: ${{ steps.beam.outputs.elixir-version }}
  otp-version:
    description: "The OTP version used in the setup"
    value: ${{ steps.beam.outputs.otp-version }}
runs:
  using: "composite"
  steps:
    - name: Setup Elixir and OTP
      id: beam
      uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ inputs.cache-name-deps }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ inputs.cache-name-deps }}-

    - name: Cache compiled build
      id: cache-build
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          _build
          priv/cldr/locales
        key: ${{ runner.os }}-mix-${{ inputs.cache-name-compiled }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ inputs.cache-name-compiled }}-
          ${{ runner.os }}-mix-

    - name: Clean to rule out incremental build as a source of flakiness
      if: github.run_attempt > 3
      run: |
        mix deps.clean --all
        mix clean
      shell: sh

    - name: Install dependencies
      run: mix deps.get
      shell: sh
