name: Check paths

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      githubfolder:
        description: "changes to .github folder"
        value: ${{ jobs.check_paths.outputs.githubfolder }}

permissions:
  contents: read

jobs:
  check_paths:
    runs-on: ubuntu-24.04
    outputs:
      githubfolder: ${{ steps.filter.outputs.githubfolder }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          base: "main" # needed to set as a called workflow does not have direct access to repository.default_branch
          filters: |
            githubfolder:
              - '.github/**'
