name: iOS Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: macos-15

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run tests
        working-directory: ios/TeslaMateApp
        run: |
          set -o pipefail
          xcodebuild test \
            -project TeslaMateApp.xcodeproj \
            -scheme TeslaMateApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -resultBundlePath TestResults \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
