name: Spell check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  spell_check:
    name: Spell check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Spell check
        uses: crate-ci/typos@f8a58b6b53f2279f71eb605f03a4ae4d10608f45 # v1.47.0
